version: '3'
services:
  insurance:
    container_name: insurance-service
    env_file:
      - .env
    image: "insurance:${TAG}"
    build:
      context: .
    ports:
      - "4000:4000"
      - "4002:4002"
      - "8384:8384"
    expose:
      - "8384"
      - "4002"
      - "4000"
    networks:
      - test
    depends_on:
      - db

  db:
    container_name: mysql-db
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $PASSWORD_DATABASE
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d/
      - ./db_data:/var/lib/mysql
      - ./database:/tmp/database
    command: mysqld --init-file="/tmp/database/init-script.sql"
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - test

networks:
  test: